### PR TITLE
Bumping version of roadrunner

### PR DESCRIPTION
**Pull request by vladitot**
Hey! I want to use at the same time laravel-roadrunner-bridge and php-grpc packages in one project. 
But I see version conflicts. So now im trying to resolve this conflict.

### CODE REVIEW

**Comment by wolfy-j** [comment]
We have not migrated the GRPC to RR2 yet. It will be part of main build in the nearest future.

**Comment by vladitot** [comment]
@wolfy-j How soon it can be?

**Comment by wolfy-j** [comment]
@48d90782

**Comment by 48d90782** [comment]
> @wolfy-j How soon it can be?
@vladitot Here is our timeline https://github.com/orgs/spiral/projects/2, grpc support for the RR2 planned for the 2021-05-11 release.

**Pull request closed without merging**
