### PR TITLE
fix the slash error.

### PR DESCRIPTION
**Pull request by oneslash**
@wolfy-j, I did a very stupid mistake, unit tests were not testing this. 

This time I compiled and tested with the app. I am sorry for the inconvenience.

### CODE REVIEW

**Comment by oneslash** [comment]
I also `chmod +x` for build.sh

**Comment by wolfy-j** [comment]
Sounds like we are doing 3 patch releases today.

**Comment by wolfy-j** [comment]
Nothing else is missing?

**Comment by oneslash** [comment]
I don’t see anything now, which is missing

**Comment by wolfy-j** [comment]
It’s out.

**Pull request merged**
