### PR TITLE
feat(proto): add support for multiple proto files

### PR DESCRIPTION
**Pull request by russianlagman**
added possibility to specify multiple .proto files in rr.yaml config

### CODE REVIEW

**Comment by russianlagman** [comment]
@rustatian trying to add more tests here, but tests fail on the go 1.17.1 with the bundled certs

```=== RUN   Test_Proxy_Error
    proxy_test.go:66: 
        	Error Trace:	proxy_test.go:66
        	Error:      	Not equal: 
        	            	expected: "nothing here"
        	            	actual  : "connection error: desc = \"transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs instead\""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-nothing here
        	            	+connection error: desc = "transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs instead"
        	Test:       	Test_Proxy_Error
    proxy_test.go:67: 
        	Error Trace:	proxy_test.go:67
        	Error:      	Not equal: 
        	            	expected: 0x5
        	            	actual  : 0xe
        	Test:       	Test_Proxy_Error
    proxy_test.go:73: 
        	Error Trace:	proxy_test.go:73
        	Error:      	Not equal: 
        	            	expected: "main exception message"
        	            	actual  : "connection error: desc = \"transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs instead\""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-main exception message
        	            	+connection error: desc = "transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs instead"
        	Test:       	Test_Proxy_Error
    proxy_test.go:74: 
        	Error Trace:	proxy_test.go:74
        	Error:      	Not equal: 
        	            	expected: 0x3
        	            	actual  : 0xe
        	Test:       	Test_Proxy_Error
--- FAIL: Test_Proxy_Error (0.15s)
```

**Comment by rustatian** [comment]
@russianlagman I guess you can use the certs from the RR2. I fixed this issue there.

**Comment by russianlagman** [comment]
@rustatian can't add more tests without upgrading the grpc-go package: generated go client is not compatible with the existing version

**Comment by rustatian** [comment]
> @rustatian can't add more tests without upgrading the grpc-go package: generated go client is not compatible with the existing version
> 
> ```
> PASS
> coverage: 82.1% of statements
> ok  	github.com/spiral/php-grpc	2.160s
> ```

Ok, thanks, I'll have a look a little bit later.

**Review by rustatian — APPROVED** [review]
lgtm

**Comment by rustatian** [comment]
Thanks @russianlagman

**Pull request merged**
