### PR TITLE
Support sending HTTP headers

### PR DESCRIPTION
**Pull request by wolfgang-braun**
- Addresses issue: https://github.com/spiral/php-grpc/issues/28
- Functionality: Adds a metadata array reference to the PHP service classes which will be used by the go proxy to set server response headers

### CODE REVIEW

**Comment by wolfy-j** [comment]
This will cause major BC change on PHP end. Golang seems ok, let me think how to deal with it. I think the easiest way is to carry response metadata as reference inside the context.

**Comment by wolfgang-braun** [comment]
@wolfy-j changed it like you suggested.

**Comment by wolfy-j** [comment]
Hi, I would like not to extend the ContextInterface but rather carry mutable outgoing headers object in one of the cotext values. Are you OK if I'll merge your request and then do such change by myself?

**Comment by wolfgang-braun** [comment]
Okay. Sure!

**Comment by wolfy-j** [comment]
I'll work on it and hopefully few other updates later today and this weekend.

**Comment by wolfgang-braun** [comment]
Sounds great. 

btw some thoughts on that:
Currently any object-reference in [Context::values](https://github.com/spiral/php-grpc/blob/master/src/Context.php#L15) will get lost by calling [Context::withValue()](https://github.com/spiral/php-grpc/blob/master/src/Context.php#L35).
This is fine because Context is meant to be immutable.

In RPC-methods (e.g. `authenticate`) we're currently not able to return a new context instance. So calling Context::withValue() there, wouldn't affect the outgoing context.

I see 3 options: 
- either we define that headers can only be set in interceptors (which return a ctx instance)
- or we make the ctx instance partly mutable 
- or we change the RPC methods to support returning an ctx instance.


I think it's a valid requirement to be able to set outgoing headers also in RPC-methods and not only in interceptors.

**Comment by wolfy-j** [comment]
WithValue will only overwrite one value, so you can mutable object if no one overwrites it. The ability to overwrite value is pretty useful as you can "mock" outgoing headers object for the testing or other purposes.

**Comment by wolfy-j** [comment]
```php
$context->getValue(Context::METADATA_OUTPUT)->set('key', 'value');
```

I've seen such an approach in PSR-7 middleware collection.

**Pull request merged**
