### PR TITLE
Possibility to send errors details

### LINKED ISSUE #21: Rich error model
Hi, thanks for the project!!
Is there are possible to use rich error model?
https://www.grpc.io/docs/guides/error/
https://cloud.google.com/apis/design/errors#error_model

### PR DESCRIPTION
**Pull request by evsign**
Closes #21

### CODE REVIEW

**Comment by wolfy-j** [comment]
Please add tests. Thank you for PR

**Comment by evsign** [comment]
@wolfy-j take a look please. Need more or this will be enough.

**Comment by wolfy-j** [comment]
Changed looks good, I can merge them now. Do you want to do anything with https://github.com/spiral/php-grpc/blob/master/cmd/rr-grpc/grpc/debug.go#L80 
(realtime log) or it is not compatible with arbitrary error messages?

**Comment by wolfy-j** [comment]
I will try to pack new release next week, I want to add support for new Metrics service with exposure to Prometheus.

**Pull request merged**
